
######################## default configuration ####################
baseURL = "https://sg.com.mx/explorer-day"
title = "Explorer Day"
enableRobotsTXT = true
RemovePathAccents = true

#googleAnalytics = "UA-21077034-25"

theme = "explorer-day"
# post pagination
paginate = "10"

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"

# output
[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


############################## navigation ###############################
[menu]


  [[menu.main]]
  name = "Agenda"
  URL = "agenda"
  weight = 2

  [[menu.main]]
  name = "Conferencistas"
  URL = "speakers"
  weight = 3

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 6



#################### default parameters ################################
[params]
logo = "images/SG-EXPLORER DAY_logo.png"
home = "Home"

# Meta data
description = "Explorer Day"
image = "images/card-2022.jpg"
images = ["images/card-2022.jpg"]
twitter_user = "@revistasg"
email = "eventos@sg.com.mx"
author = "Software Guru"

disclaimer = ""

# Navigation button
[params.navigation_button]
enable = true
label = "Registro"
link = "#"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/RevistaSG"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/c/softwareguru"


[[params.social]]
icon = "tf-ion-social-octocat"
link = "https://github.com/softwareguru"

[[params.social]]
icon = "tf-ion-android-mail"
link = "mailto:eventos@sg.com.mx"


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
[[params.plugins.css]]
link ="/plugins/color-switcher-design/color-switcher-design.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "/plugins/flaticon/flaticon.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"



# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.slim.min.js" 

[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="https://kit.fontawesome.com/2e09285ae6.js"

[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"


