
######################## default configuration ####################
baseURL = "https://sg.com.mx/explorerday/"
title = "SG Explorer Day"
enableRobotsTXT = true
RemovePathAccents = true

theme = "explorerday"
# post pagination
paginate = "10"

[taxonomies]
speaker = "speakers"

[imaging]
resampleFilter = "CatmullRom"
quality = 80
anchor = "smart"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# output
[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true     

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

############################## navigation ###############################
[menu]


  [[menu.main]]
  name = "Agenda"
  URL = "agenda"
  weight = 2

  [[menu.main]]
  name = "Conferencistas"
  URL = "speakers"
  weight = 3

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 6



#################### default parameters ################################
[params]
logo = "/images/logo-simple.svg"
home = "Home"

# Meta data
description = "SG Explorer Day"
image = "images/card.jpg"
images = ["images/card.jpg"]
twitter_user = "@revistasg"
email = "eventos@sg.com.mx"
author = "Software Guru"

start_date = "2022-05-17T10:00-05:00"
end_date = "2022-05-17T17:00-05:00"

disclaimer = ""

[params.ui]
breadcrumb_disable = true
footer_about_disable = false
navbar_translucent_over_cover_disable = false

# Navigation button
[params.navigation_button]
enable = true
label = "Registro"
link = "https://sg1.run/sgexplorerday"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/RevistaSG"

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/c/softwareguru"


[[params.social]]
icon = "tf-ion-social-octocat"
link = "https://github.com/softwareguru"

[[params.social]]
icon = "tf-ion-android-mail"
link = "mailto:eventos@sg.com.mx"


[[params.links.media]]
    name = "Check us on LinkedIn"
    url = "https://www.linkedin.com/company/softwareguru"
    icon = "fab fa-linkedin-in"
[[params.links.media]]
    name = "Watch us on YouTube"
    url = "https://www.youtube.com/c/softwareguru"
    icon = "fab fa-youtube"

[[params.links.footer]]
    name = "Código de conducta"
    url = "/explorerday/coc"
[[params.links.footer]]
    name = "Política de privacidad"
    url = "/explorerday/politica-de-privacidad"


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"



# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.slim.min.js" 


[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"


